name: Build on Windows

on:
  push:
    branches:
      - devel
  pull_request:

jobs:
  build-windows:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: windows-latest, r: 'devel' }
          - { os: ubuntu-latest, r: 'devel' }
          - { os: macOS-latest, r: 'devel' }

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          
      - name: Install Bioconductor devel
        run: |
          Rscript -e 'install.packages("BiocManager")'
          Rscript -e 'BiocManager::install(version = "devel")'

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: bioc::BiocGenerics

      - name: Build the package
        shell: cmd
        run: R CMD build .

      - name: Run tests
        run: R CMD check *.tar.gz --no-manual
