name: Build on Windows

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4"

      # Step 3: Install dependencies
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      # Step 4: Build the package
      - name: Build the package
        run: R CMD build .

