name: Build on Windows

on:
  push:
    branches:
      - main
      - master
      - devel
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config:
          - { os: windows-latest, r: 'devel' }

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          
      # Step 3: Install Bioconductor devel
      - name: Install Bioconductor devel
        run: |
          Rscript -e 'install.packages("BiocManager")'
          Rscript -e 'BiocManager::install(version = "devel")'

      # Step 4: Install dependencies
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: bioc::BiocGenerics

      # Step 5: Build the package
      - name: Build the package
        shell: cmd
        run: R CMD build .

